[general]
import = [
	"~/.config/alacritty/colors.toml" # Color scheme
]

[font]
size = 5.0
normal = { family = "JetBrainsMono Nerd Font" }

[window]
padding = { x = 5, y= 5 }
opacity = 0.95

[scrolling]
history = 10000

[env]
WINIT_X11_SCALE_FACTOR = "1.66"
TERM = "xterm-256color"
