# Colors (Vesper)
# Source https://github.com/raunofreiberg/vesper

[colors.primary]
background = '#080808'
foreground = '#ffffff'

[colors.normal]
black   = '#080808'
red     = '#f5a191'
green   = '#90b99f'
yellow  = '#e6b99d'
blue    = '#aca1cf'
magenta = '#e29eca'
cyan    = '#ea83a5'
white   = '#a0a0a0'

[colors.bright]
black   = '#7e7e7e'
red     = '#ff8080'
green   = '#99ffe4'
yellow  = '#ffc799'
blue    = '#b9aeda'
magenta = '#ecaad6'
cyan    = '#f591b2'
white   = '#ffffff'
